6: Remove grey text from gdocs
StampyAI/GDocsRelatedThings pull request #23
Opened 2023-04-26 13:15 UTC by mruwnik

https://github.com/StampyAI/GDocsRelatedThings/issues/6

2023-04-26 14:31 UTC, Aprillion requested changes

2023-04-26 14:31 UTC, Aprillion commented on parser/parser.js
> +    rgbVals && rgbVals.every((val) => Math.abs(val - rgbVals[0]) <= tolerance)
aah, let's not exclude explicitly-set-color black text... 🖤 

looking at Google Docs color picker, the first 2 options (0% and 26% brightness) look dark enough to keep as "normal" text IMHO, I would only exclude the other options (third one is 40% => anyting above 0.3 can be excluded .. but probably check with @plexish or with all editors on Discord)

<img width="316" alt="Screenshot 2023-04-26 at 16 13 24" src="https://user-images.githubusercontent.com/1087670/234605257-a1d1b3b9-be3a-447c-b5a6-70ceb4c9b47e.png">

2023-04-26 14:34 UTC, Aprillion commented on parser/parser.js
> +  const tolerance = 0.01;
🤔 do we want to be this fancy? default gray colors in GDocs don't need "tolerance" between RGB values, `r === g && r === b && r >= 0.3` might be a more readable condition maybe..

2023-04-26 15:47 UTC, mruwnik commented on parser/parser.js
> +  const tolerance = 0.01;
they're floats, and I don't trust them to be equal :/ Though I suppose wrapping them with a round and toString would work. Or am I overthinking it?

2023-04-27 07:15 UTC, Aprillion commented on parser/parser.js
> +  const tolerance = 0.01;
I've never seen color channels as floats before, so no idea what to expect 😁

2023-04-27 07:16 UTC, mruwnik commented on parser/parser.js
> +  const tolerance = 0.01;
yup, they normalise them to be between 0-1, for some reason :D

2023-04-27 07:17 UTC, Aprillion commented on parser/__tests__/parser.test.js
> +    // really light grey or white isn't removed
huh? why not?

2023-04-27 08:38 UTC, mruwnik commented on parser/__tests__/parser.test.js
> +    // really light grey or white isn't removed
coz it's hard to differentiate from black. That being said, the cutoffs were too limiting, so I changed it to (0.02; 0.98) - that should suffice

2023-04-27 08:39 UTC, mruwnik commented on parser/__tests__/parser.test.js
> +    // really light grey or white isn't removed
this handles all the available greys in gdocs, at least the ones that can currently be selected

2023-04-27 08:45 UTC, Aprillion commented on parser/__tests__/parser.test.js
> +    // really light grey or white isn't removed
I mean, why not exclude white text?!?

2023-04-27 08:46 UTC, Aprillion commented on parser/__tests__/parser.test.js
> +    // non gray is removed
non gray is *not* removed..

2023-04-27 08:47 UTC, Aprillion approved these changes
not sure why we want to include white text, but whatever, it's good enough to merge :D

2023-04-27 10:28 UTC, mruwnik commented on parser/__tests__/parser.test.js
> +    // really light grey or white isn't removed
ah. That :D I assumed that if someone wants to have explicity white text for some obscure reason, then who am I to disallow it :D

2023-04-27 11:14 UTC, merged

2023-05-02 12:11 UTC, plexish commented on parser/parser.js
> +    rgbVals && rgbVals.every((val) => Math.abs(val - rgbVals[0]) <= tolerance)
seems reasonable