Use cloudflare for image storage
StampyAI/GDocsRelatedThings pull request #50
Opened 2023-07-10 12:26 UTC by mruwnik

this will create new copies of all images each time the doc gets processeed, which is annoying. The images have metadata, which could be used to find and destroy older images, maybe? Either way, it shouldn't be an issue, as CF counts images for billing in 100k increments

2023-07-11 10:55 UTC, Aprillion requested changes

2023-07-11 10:55 UTC, Aprillion commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
🤔 we cannot delete old images right away, because those are used in the UI before the new ones get propagated

but only adding images and never deleting anything is NOT the way to go, not even temporary because there will be no way to find out which ones are safe to delete later when we will want to delete the old ones

would it be possible to at least add some version number or date and delete all images in a given UIID that are not the latest version (before uploading the next version => we will have latest 2 versions, but not a million)?

2023-07-11 10:58 UTC, Aprillion commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
..if not possible to do it at least half-assed, I would rather say that Google Docs solution does not support images at all, IMHO append-only solution for image storage is really really NOT good 🤷

2023-07-11 11:03 UTC, Aprillion commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
..if not possible, then convincing editors to use some external image service and insert links into gdocs and rendering embeds (like for youtube videos) sounds like a better workaround

2023-07-11 12:09 UTC, mruwnik commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
cloudflare images don't seem to have a search function. At least I can't find it. What could be done, though, is to have another script that will go through ALL the images, group them by UIID and upload date (it's in the metadata) and then delete all the ones that are from a previous upload. This could be run e.g. once daily or whatever

2023-07-11 14:08 UTC, Aprillion commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
hmmm 🤔 sounds good-enough, but not sure. I will leave it up to other reviewers 😅

2023-07-11 14:33 UTC, mruwnik commented on parser/parser.js
> +      img.imageProperties.contentUri = await uploadImage(
I added a script to prune images from earlier versions

2023-07-12 08:12 UTC, Aprillion approved these changes
looks ready for testing in production 🍀

2023-07-12 08:47 UTC, merged